services:
  db:
    image: postgres:15
    container_name: smartshape-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=smartshape
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin